# Generated by Django 3.2 on 2022-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220107_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReturn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'accounts_user',
                'managed': False,
            },
        ),
    ]
