# Generated by Django 3.2 on 2021-12-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.TextField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CTF', 'CTF'), ('Study', 'Study'), ('Project', 'Project')], max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('createDate', models.DateField(db_column='createDate')),
                ('description', models.CharField(max_length=100)),
                ('startDate', models.DateField(db_column='startDate')),
                ('endDate', models.DateField(db_column='endDate')),
                ('currentState', models.PositiveIntegerField(choices=[(0, '0 : 예정'), (1, '1 : 진행'), (2, '2 : 종료')], db_column='currentState', default=0)),
                ('viewerNum', models.PositiveIntegerField(db_column='viewerNum', default=0)),
            ],
            options={
                'db_table': 'activity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='activity.activity')),
                ('tag_id', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='acti', to='activity.tag')),
            ],
            options={
                'db_table': 'activity_tag',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activity.activity')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='acti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_participant',
                'managed': True,
            },
        ),
    ]
