# Generated by Django 3.2 on 2021-11-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('CTF', 'CTF'), ('Study', 'Study'), ('Project', 'Project')], max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('createDate', models.DateField(db_column='createDate')),
                ('description', models.CharField(max_length=65)),
                ('startDate', models.DateField(db_column='startDate')),
                ('endDate', models.DateField(db_column='endDate')),
                ('currentState', models.PositiveIntegerField(choices=[(0, '0 : 예정'), (1, '1 : 진행'), (2, '2 : 종료')], db_column='currentState', default=0)),
                ('viewerNum', models.PositiveIntegerField(db_column='viewerNum', default=0)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'activity_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
