# Generated by Django 3.2.5 on 2021-08-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('createdate', models.DateField(db_column='createDate')),
                ('introduce', models.CharField(max_length=65)),
                ('startdate', models.DateField(db_column='startDate')),
                ('enddate', models.DateField(db_column='endDate')),
                ('currentstate', models.PositiveIntegerField(db_column='currentState')),
                ('viewernum', models.PositiveIntegerField(db_column='viewerNum')),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
