# Generated by Django 3.2 on 2022-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_auth_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='auth_string',
        ),
        migrations.AddField(
            model_name='activity',
            name='authString',
            field=models.CharField(db_column='authString', default=None, max_length=128),
            preserve_default=False,
        ),
    ]
