# Generated by Django 3.2.5 on 2021-08-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='createdate',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='currentstate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='viewernum',
        ),
        migrations.AddField(
            model_name='activity',
            name='currentState',
            field=models.PositiveIntegerField(db_column='currentState', default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='viewerNum',
            field=models.PositiveIntegerField(db_column='viewerNum', default=0),
        ),
    ]
