# Generated by Django 3.2 on 2022-02-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20220127_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='authString',
            field=models.CharField(blank=True, db_column='authString', max_length=128, null=True),
        ),
    ]
