# Generated by Django 3.2.5 on 2021-08-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20210801_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': False},
        ),
    ]
