# Generated by Django 3.2.5 on 2021-08-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': False},
        ),
    ]
